# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d4df6921406771f7e37e8a43eb28b66f353f20db3ba1c6c6b8f1da4a511d6f4dafc653febf9df4e2701e323574fc763ef0792e20f71fb76b6c88edcbda445a7

test:
  secret_key_base: ed2ef7d22475492936efa14e89e693a41da6d30d9a73fef89226fe54fa7778a73dae0d21e7ca7e116327f482a938f3a4266bbf70b446ec3b19fd802600227782

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
